### ISSUE TITLE
Linux WebXR

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#147]
Credits to **SketchStick** and **haagch** for the work on this! We got Linux WebXR working on Discord, but the patch needs to be put upstream. This was in Arch Linux:

![capture 9](https://user-images.githubusercontent.com/6926057/42162346-589ca482-7dcc-11e8-9309-232fe6af0424.PNG)

We need to put this `LD_PRELOAD` into [binding.gyp](https://github.com/webmixedreality/exokit/blob/d009c0d32138c67d598d4807da17a8e54c6fdae4/binding.gyp#L260), and update the [Dockerfile](https://github.com/webmixedreality/exokit/blob/d009c0d32138c67d598d4807da17a8e54c6fdae4/Dockerfile#L6) and docs with the newly required libs. Other than that it seemed to work in SteamVR with no code changes.

Could also use help testing this patch on Linux VR rigs 💪.

**Comment by ChristophHaag** [comment]
Or in text form, link to `Xcursor`, `Xinerama`, `Xxf86vm`, `Xrandr`, `Xi` and - not shown in the image because it only came up later - `asound`.

The second issue was the included libfreetype and libfontconfig conflicting with the system's libharfbuzz.so. Either include libharfbuzz too or don't package libfreetype and libfontconfig - these two are perfectly reasonable depdencies to have.

The third is why I preloaded libexpat.so - the radeonsi driver uses it to parse its xml config file (drirc), but segfaults when skia has been loaded, because skia uses and includes (presumably) a different version of libexpat.

**Comment by modulesio** [comment]
Looks like we need to also build with system skia for linux, so that we don't need a preload override for libexpat.
