### ISSUE TITLE
Remove unbound HTML media elements, assume native bindings.

### ISSUE THREAD

**Issue by ngokevin** [webmixedreality/exokit#175]
In a thread somewhere, @modulesio said there was some unused code of unbound media elements in case we wanted to use Exokit without native bindings.

But now we drop that case and always just assume native bindings? Then we can clean up some code in core.js...moving the binding code to DOM.js, and removing the old classes from DOM.js.

**Comment by modulesio** [comment]
Correct, I think classes like [this](https://github.com/webmixedreality/exokit/blob/master/src/DOM.js#L1633) are now dead stubs for all use cases, because in `setNativeBindings` we [override the stub](https://github.com/webmixedreality/exokit/blob/master/core.js#L1874).

This is true for Audio and Video elements as well
