### ISSUE TITLE
Unit test MutationObserver.

### ISSUE THREAD

**Issue by ngokevin** [webmixedreality/exokit#183]
I'm working on this at the moment.

I might have been getting issues with the observer missing some mutations (children getting appended), gonna unit test it to see if that's the case.

**Comment by modulesio** [comment]
I've been considering a redesign of how `MutationObserver` is implemented to instead bubble up mutations to the nearest observer, rather than trying to maintain 100% accurate listener bindings for subtrees as they change. That's how it currently works and it's fraught with corner cases.

If there's a failing case, refactoring to that approach might be the fix, or at least make it more debuggable.
