### ISSUE TITLE
Issues with core-js es6 Promise polyfill.

### ISSUE THREAD

**Issue by ngokevin** [webmixedreality/exokit#433]
Test case: https://webvr.soundboxing.co/

Firefox and Exokit both get routed to use the es6 Promise polyfill, commonly used in Babel projects. There are issues with `state.reactions.push(reaction)` (or `this._c.push`) where `state.reactions` (or `this._c`) is undefined in Exokit, whereas it should be an array defined in the internal Promise constructor. Works in Firefox.

Maybe the native Promise objects is clashing with the polyfill Promise somewhere, or something to do with sandboxing. Looking into it.

**Comment by ngokevin** [comment]
Specifically: https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.promise.js

**Comment by modulesio** [comment]
Possibly useful hunch is that it's a `instanceof` of the `Promise` species or some `Promise`-releated global. E.g. something like this not passing the correct test: https://github.com/zloirock/core-js/blob/af00ffd5ba3c0485f5c1fad73a11d128d60f2e68/packages/core-js/modules/es.promise.js#L53

I've seen this before with differences in species inside/outside the `window` context vs the top level and there is a whitelisted species converter used for handling this:
https://github.com/webmixedreality/exokit/blob/3190804edb0f63247f8df6c8ee2c8ae25866c32b/src/utils.js#L89

The way to know if this is the problem is if `instanceof` seems to not be returning the correct thing.

**Comment by ngokevin** [comment]
So in this case `_normalizeBuffer` is taking a top-level Promise (from `window-fetch`) and setting the prototype of it to the window's Promise (the polyfill). I believe that is what causing issues. If I remove `Promise` from the `_normalizeBuffer`, the application moves on. What cases would we need to convert the Promise?

**Comment by modulesio** [comment]
The conversion needs to happen:

- when we get some native object like `Promise` or `Uint8Array` from the `node` (e.g. let's say `fetch`) and we want to pass it through to the `window` context
- whenever `window` generates some native object like `Uint8Array` and passes it back to the `node` system e.g. `http.write`

I don't think anything explodes if you fail to do this, but `instanceof` fails otherwise, and a lot of important things do `instanceof`.

I can see how this would be a problem if code straight up rewrites the top-level `Promise` though. We should probably limit the conversion to the actual intended object specii rather than testing name.

Sidenote: The reason for this is basically because node's `vm` module is (was?) slow (breaks a lot of important ops at the context boundary), so we have a faster one in place called [`vm-one`](https://github.com/modulesio/vm-one).
