### ISSUE TITLE
CEF: Setting iframe width / height after onload doesn't change texture size

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#600]
![image](https://user-images.githubusercontent.com/6830845/48647918-61a84380-e9e5-11e8-95a8-52e84bf43d0a.png)
Note: this works as expected if the width/height is set outside the `iframe.onload = ...` so a bit of an edge case.

Repro: 
`node . https://mountainous-tail.glitch.me/`

**Comment by shaneharris** [comment]
Also if you set the `iframe.src` property you have to set the `iframe.width`/`iframe.height` properties again to maintain a certain height - i think i have a fix for that though

**Comment by modulesio** [comment]
Is that fix PR-able?

**Comment by shaneharris** [comment]
I had a look but i couldn't see an easy way to fix. im doing some more work on it this morning though

**Comment by modulesio** [comment]
Should be fixed with https://github.com/webmixedreality/exokit/pull/577/commits/e3191c57efdf38d020ce51f8196069610a8c7119, https://github.com/webmixedreality/exokit/pull/577/commits/2f232a3dce6a737988fb65101d7bb375f0dddc7d, https://github.com/webmixedreality/exokit/pull/577/commits/567c53b71170543d0dc0f2a93364af6afac7c320
